const C=document.getElementById('game'),ctx=C.getContext('2d');let W,H,dpr=1;
const ui={menu:document.getElementById('menu'),upgrade:document.getElementById('upgrade'),pause:document.getElementById('pause'),over:document.getElementById('gameover'),cards:document.getElementById('cards'),toast:document.getElementById('toast')};
const keys={},mouse={x:0,y:0,down:false};let state='menu',last=0,shake=0,save=JSON.parse(localStorage.getItem('neonRiftSave')||'{"high":0,"shards":0}');
const upgrades=[
{name:'Overclock',icon:'⚡',desc:'Fire rate +28%. Every fifth shot becomes a piercing bolt.',tag:'WEAPON',apply:p=>{p.fireRate*=.72;p.pierce++;}},
{name:'Void Rounds',icon:'◈',desc:'Damage +35% and projectiles become larger.',tag:'DAMAGE',apply:p=>{p.damage*=1.35;p.bulletSize+=1;}},
{name:'Nanite Skin',icon:'✦',desc:'Max HP +35 and instantly heal 35%.',tag:'SURVIVAL',apply:p=>{p.maxHp+=35;p.hp=Math.min(p.maxHp,p.hp+35);}},
{name:'Grav Boots',icon:'⌁',desc:'Move speed +22% and dash cooldown -20%.',tag:'MOBILITY',apply:p=>{p.speed*=1.22;p.dashCd*=.8;}},
{name:'Singularity',icon:'●',desc:'Every kill has a 9% chance to pull nearby enemies and explode.',tag:'ARCANE',apply:p=>{p.singularity=true;}},
{name:'Blood Circuit',icon:'♥',desc:'Heal 1.5 HP per kill. Critical chance +10%.',tag:'HYBRID',apply:p=>{p.lifeSteal+=1.5;p.crit+=.1;}},
{name:'Twin Core',icon:'⟁',desc:'Fire a second shot at a slight angle. -8% damage.',tag:'WEAPON',apply:p=>{p.multishot++;p.damage*=.92;}},
{name:'Rift Battery',icon:'☄',desc:'Ultimate gains 40% more charge and starts with 20%.',tag:'ULTIMATE',apply:p=>{p.ultGain*=1.4;p.ult=Math.min(100,p.ult+20);}},
{name:'Glass Cannon',icon:'◇',desc:'Damage +80%, but max HP -20%.',tag:'RISK',apply:p=>{p.damage*=1.8;p.maxHp*=.8;p.hp=Math.min(p.hp,p.maxHp);}}
];
let p,enemies=[],bullets=[],particles=[],orbs=[],texts=[],wave=1,waveTimer=0,score=0,kills=0,level=1,xp=0,xpNeed=100,shards=0,totalTime=0,boss=null,spawnClock=0,shots=0;
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;C.width=W*dpr;C.height=H*dpr;C.style.width=W+'px';C.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(){p={x:W/2,y:H/2,r:13,hp:100,maxHp:100,speed:290,damage:18,fireRate:170,bulletSpeed:780,bulletSize:4,pierce:0,multishot:0,crit:.08,dashCd:1.0,dashT:0,dashPower:780,dashTime:0,ult:0,ultGain:1,lifeSteal:0,singularity:false,inv:0,shotT:0};enemies=[];bullets=[];particles=[];orbs=[];texts=[];wave=1;waveTimer=0;score=0;kills=0;level=1;xp=0;xpNeed=100;shards=0;totalTime=0;boss=null;spawnClock=0;shots=0;state='play';ui.menu.classList.add('hidden');ui.over.classList.add('hidden');ui.pause.classList.add('hidden');toast('WAVE 1 // SURVIVE',1400)}
function toast(t,ms=1000){ui.toast.textContent=t;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),ms)}
function spawn(){if(boss)return;const a=Math.random()*Math.PI*2,edge=Math.floor(Math.random()*4),pad=60;let x,y;if(edge===0){x=-pad;y=Math.random()*H}else if(edge===1){x=W+pad;y=Math.random()*H}else if(edge===2){x=Math.random()*W;y=-pad}else{x=Math.random()*W;y=H+pad}
let roll=Math.random(),type=roll<.58?'drone':roll<.8?'stalker':roll<.94?'tank':'splitter';let scale=1+wave*.075;let e={x,y,r:12,hp:35*scale,max:35*scale,speed:75+wave*2,damage:10+wave*.5,type,hit:0,elite:false};if(Math.random()<Math.min(.12,wave*.012)){e.elite=true;e.r*=1.45;e.hp*=3;e.max=e.hp;e.speed*=1.12;e.damage*=1.5}if(type==='tank'){e.r=21;e.hp*=2.8;e.speed*=.52}if(type==='stalker'){e.speed*=1.45;e.hp*=.7}if(type==='splitter'){e.hp*=1.25;e.speed*=.8}enemies.push(e)}
function spawnBoss(){boss={x:W/2,y:-80,r:54,hp:1600+wave*450,max:1600+wave*450,t:0};toast('⚠ RIFT TITAN // BOSS INBOUND',2200);for(let i=0;i<8;i++)spawn()}
function shoot(){if(p.shotT>0||state!=='play')return;p.shotT=p.fireRate;let a=Math.atan2(mouse.y-p.y,mouse.x-p.x);let count=1+p.multishot;for(let i=0;i<count;i++){let off=count===1?0:(i-(count-1)/2)*.11;let crit=Math.random()<p.crit;bullets.push({x:p.x+Math.cos(a+off)*18,y:p.y+Math.sin(a+off)*18,vx:Math.cos(a+off)*p.bulletSpeed,vy:Math.sin(a+off)*p.bulletSpeed,life:1.3,dmg:p.damage*(crit?2:1),pierce:p.pierce,crit})}shots++;p.ult=Math.min(100,p.ult+.7*p.ultGain)}
function dash(){if(p.dashT>0||state!=='play')return;let dx=(keys.a||keys.ArrowLeft?-1:0)+(keys.d||keys.ArrowRight?1:0),dy=(keys.w||keys.ArrowUp?-1:0)+(keys.s||keys.ArrowDown?1:0);if(!dx&&!dy){dx=Math.cos(Math.atan2(mouse.y-p.y,mouse.x-p.x));dy=Math.sin(Math.atan2(mouse.y-p.y,mouse.x-p.x))}let l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;p.dashT=p.dashCd;p.dashTime=.16;p.inv=.24;p.x+=dx*80;p.y+=dy*80;for(let i=0;i<18;i++)particle(p.x,p.y,dx*-120+Math.random()*80-40,dy*-120+Math.random()*80-40,Math.random()*18+4,'#55efff')}
function ult(){if(p.ult<100||state!=='play')return;p.ult=0;shake=18;for(const e of enemies)e.hp-=p.damage*8; if(boss)boss.hp-=p.damage*20;for(let i=0;i<120;i++){let a=Math.random()*Math.PI*2,r=Math.random()*180;particle(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,Math.cos(a)*200,Math.sin(a)*200,Math.random()*12+2,'#b84dff')}toast('OVERDRIVE // REALITY SHRED',1300)}
function gainXP(n){xp+=n;while(xp>=xpNeed){xp-=xpNeed;level++;xpNeed=Math.floor(xpNeed*1.32);showUpgrade()}}
function showUpgrade(){state='upgrade';ui.upgrade.classList.remove('hidden');ui.cards.innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let d=document.createElement('div');d.className='card';d.innerHTML='<div class="icon">'+u.icon+'</div><div class="tag">'+u.tag+'</div><h3>'+u.name+'</h3><p>'+u.desc+'</p>';d.onclick=()=>{u.apply(p);ui.upgrade.classList.add('hidden');state='play';toast(u.name.toUpperCase()+' // INSTALLED',900)};ui.cards.appendChild(d)})}
function kill(e){kills++;score+=Math.floor(e.max*(e.elite?3:1));shards+=e.elite?3:1;gainXP(e.elite?32:16);p.hp=Math.min(p.maxHp,p.hp+p.lifeSteal);p.ult=Math.min(100,p.ult+(e.elite?5:1.5));for(let i=0;i<8;i++)particle(e.x,e.y,(Math.random()-.5)*180,(Math.random()-.5)*180,Math.random()*8+3,e.elite?'#ff4fd8':'#45e8ff');if(p.singularity&&Math.random()<.09){for(const q of enemies){let d=Math.hypot(q.x-e.x,q.y-e.y);if(d<130)q.hp-=p.damage*2}shake+=4}}
function particle(x,y,vx,vy,r,c){particles.push({x,y,vx,vy,r,life:.5+Math.random()*.7,max:.9,c})}
function update(dt){totalTime+=dt;waveTimer+=dt;if(p.shotT>0)p.shotT-=dt;if(p.dashT>0)p.dashT-=dt;if(p.inv>0)p.inv-=dt;if(p.dashTime>0)p.dashTime-=dt;
let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),l=Math.hypot(dx,dy)||1;p.x+=dx/l*p.speed*dt;p.y+=dy/l*p.speed*dt;p.x=Math.max(18,Math.min(W-18,p.x));p.y=Math.max(18,Math.min(H-18,p.y));
if(mouse.down)shoot();spawnClock-=dt;if(spawnClock<=0){let rate=Math.max(.12,.72-wave*.018);spawnClock=rate;if(enemies.length<45+wave*2)spawn()}
if(waveTimer>28&&!boss){wave++;waveTimer=0;toast('WAVE '+wave,1000);if(wave%5===0)spawnBoss()}
for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let gone=b.life<=0||b.x<-30||b.x>W+30||b.y<-30||b.y>H+30;for(let j=enemies.length-1;j>=0&&!gone;j--){let e=enemies[j],d=Math.hypot(e.x-b.x,e.y-b.y);if(d<e.r+b.size+4){e.hp-=b.dmg;b.pierce--;b.x+=b.vx*dt*.03;particle(b.x,b.y,0,0,Math.random()*5+2,b.crit?'#fff':'#55eaff');if(e.hp<=0){kill(e);enemies.splice(j,1)}if(b.pierce<0)gone=true}}if(boss&&!gone&&Math.hypot(boss.x-b.x,boss.y-b.y)<boss.r+b.size){boss.hp-=b.dmg;b.pierce--;if(b.pierce<0)gone=true;particle(b.x,b.y,0,0,5,'#ff4fd8')}if(gone)bullets.splice(i,1)}
for(let i=enemies.length-1;i>=0;i--){let e=enemies[i],a=Math.atan2(p.y-e.y,p.x-e.x),sp=e.speed*(e.type==='stalker'&&Math.sin(totalTime*4+e.x)>.4?1.4:1);e.x+=Math.cos(a)*sp*dt;e.y+=Math.sin(a)*sp*dt;e.hit-=dt;let d=Math.hypot(p.x-e.x,p.y-e.y);if(d<p.r+e.r){if(p.inv<=0&&e.hit<=0){p.hp-=e.damage;p.inv=.45;e.hit=.6;shake+=7;for(let k=0;k<8;k++)particle(p.x,p.y,(Math.random()-.5)*150,(Math.random()-.5)*150,3,'#ff466e');if(p.hp<=0)return die()}}}
if(boss){boss.t+=dt;let a=Math.atan2(p.y-boss.y,p.x-boss.x);boss.x+=Math.cos(a)*(45+wave)*dt;boss.y+=Math.sin(a)*(45+wave)*dt;if(boss.y>H*.38)boss.y=H*.38+Math.sin(boss.t)*80;if(Math.random()<dt*(.9+wave*.03)&&enemies.length<55)spawn();if(Math.hypot(p.x-boss.x,p.y-boss.y)<p.r+boss.r*.75&&p.inv<=0){p.hp-=28*dt;shake=8}if(boss.hp<=0){score+=5000+wave*1000;shards+=20;boss=null;wave++;waveTimer=0;toast('RIFT TITAN DESTROYED // +20 SHARDS',2200);for(let i=0;i<80;i++)particle(W/2,H/2,(Math.random()-.5)*500,(Math.random()-.5)*500,Math.random()*12+2,'#ff4fd8')}}
for(let i=particles.length-1;i>=0;i--){let q=particles[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.97;q.vy*=.97;q.life-=dt;if(q.life<=0)particles.splice(i,1)}
if(shake>0)shake*=.9;updateHUD()}
function die(){state='over';save.high=Math.max(save.high,score);save.shards+=shards;localStorage.setItem('neonRiftSave',JSON.stringify(save));document.getElementById('final').textContent='Score '+score.toLocaleString()+'  •  Wave '+wave+'  •  Level '+level+'  •  Kills '+kills+'  •  High Score '+save.high.toLocaleString();ui.over.classList.remove('hidden')}
function updateHUD(){document.getElementById('wave').textContent='WAVE '+wave;document.getElementById('timer').textContent=new Date(totalTime*1000).toISOString().slice(14,19);document.getElementById('score').textContent='SCORE '+score.toLocaleString();document.getElementById('hpbar').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';document.getElementById('hptext').textContent=Math.ceil(p.hp)+' / '+Math.ceil(p.maxHp);document.getElementById('xpbar').style.width=xp/xpNeed*100+'%';document.getElementById('leveltext').textContent='LV '+level;document.getElementById('dash').textContent=p.dashT<=0?'READY':p.dashT.toFixed(1)+'s';document.getElementById('dash').className=p.dashT<=0?'ready':'';document.getElementById('ult').textContent=Math.floor(p.ult)+'%';document.getElementById('kills').textContent=kills;document.getElementById('shards').textContent=shards+(save.shards?' + '+save.shards+' BANKED':'');document.getElementById('bossWrap').style.display=boss?'block':'none';if(boss)document.getElementById('bossbar').style.width=Math.max(0,boss.hp/boss.max*100)+'%'}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);
let g=ctx.createRadialGradient(W/2,H/2,0,W/2,H/2,Math.max(W,H)*.7);g.addColorStop(0,'#101b2b');g.addColorStop(1,'#03040a');ctx.fillStyle=g;ctx.fillRect(-20,-20,W+40,H+40);
ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;let grid=60-(wave%3)*5;for(let x=(-totalTime*12)%grid;x<W;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=(-totalTime*8)%grid;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
for(const q of particles){ctx.globalAlpha=Math.max(0,q.life/q.max);ctx.fillStyle=q.c;ctx.shadowBlur=15;ctx.shadowColor=q.c;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.fill()}ctx.globalAlpha=1;
for(const b of bullets){ctx.fillStyle=b.crit?'#fff':'#59efff';ctx.shadowBlur=18;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(b.x,b.y,b.crit?b.size+2:b.size,0,7);ctx.fill()}
for(const e of enemies){let c=e.elite?'#ff42ca':e.type==='tank'?'#ff9b42':e.type==='stalker'?'#9b62ff':e.type==='splitter'?'#54ff99':'#43d9ff';ctx.fillStyle=c;ctx.shadowBlur=22;ctx.shadowColor=c;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill();ctx.fillStyle='#07101a';ctx.beginPath();ctx.arc(e.x+Math.cos(Math.atan2(p.y-e.y,p.x-e.x))*e.r*.35,e.y+Math.sin(Math.atan2(p.y-e.y,p.x-e.x))*e.r*.35,Math.max(2,e.r*.22),0,7);ctx.fill();if(e.elite){ctx.strokeStyle='#fff';ctx.globalAlpha=.6;ctx.beginPath();ctx.arc(e.x,e.y,e.r+5,0,7);ctx.stroke();ctx.globalAlpha=1}}
if(boss){ctx.fillStyle='#ff3f9e';ctx.shadowBlur=40;ctx.shadowColor='#ff3f9e';ctx.beginPath();ctx.arc(boss.x,boss.y,boss.r+Math.sin(boss.t*5)*5,0,7);ctx.fill();ctx.fillStyle='#13051a';ctx.beginPath();ctx.arc(boss.x,boss.y,boss.r*.65,0,7);ctx.fill();ctx.strokeStyle='#b65cff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(boss.x,boss.y,boss.r+12,-boss.t,boss.t+3);ctx.stroke()}
ctx.shadowBlur=30;ctx.shadowColor='#55efff';ctx.fillStyle=p.inv>0?'#fff':'#55efff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,p.r+7+Math.sin(totalTime*8)*2,0,7);ctx.stroke();ctx.restore();requestAnimationFrame(loop)}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(state==='play')update(dt);draw()}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key===' '){e.preventDefault();dash()}if(e.key.toLowerCase()==='q')ult();if(e.key.toLowerCase()==='p'){if(state==='play'){state='pause';ui.pause.classList.remove('hidden')}else if(state==='pause'){state='play';ui.pause.classList.add('hidden')}}});addEventListener('keyup',e=>keys[e.key]=false);addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});addEventListener('mousedown',()=>mouse.down=true);addEventListener('mouseup',()=>mouse.down=false);
document.getElementById('start').onclick=reset;document.getElementById('again').onclick=reset;requestAnimationFrame(loop);